### ISSUE TITLE
Create generator Rake task

### ISSUE THREAD

**Issue by Fryguy** [redhataccess/ascii_binder#1]
possibly also allow an upstream git repo to add as a remote

**Comment by nhr** [comment]
https://github.com/redhataccess/ascii_binder/pull/5 includes the groundwork for `asciibinder new`, which can perform generator functions but will not require Rake.

**Comment by nhr** [comment]
https://github.com/redhataccess/ascii_binder/pull/8 introduces the desired functionality as `asciibinder create`.

**Comment by Fryguy** [comment]
Implemented in #8
