### ISSUE TITLE
Do we still allow .adoc extensions in _topic_map.yml

### ISSUE THREAD

**Issue by bexelbie** [redhataccess/ascii_binder#105]
https://github.com/redhataccess/ascii_binder/blob/64d2e7e41e9165f343603bfc2639547d05d8256c/templates/_topic_map.yml#L10

It appears this line is incorrect and that file names should NOT include in the .adoc extension, even optionally.

Is this desired behavior?

**Comment by bexelbie** [comment]
This may actually be a bug in this line:

https://github.com/redhataccess/ascii_binder/blob/master/lib/ascii_binder/topic_entity.rb#L36

Should it really read:

`this_step = file.end_with?('.adoc') ? file : "#{file}.adoc"`

**Comment by nhr** [comment]
Good catch; fixed in https://github.com/redhataccess/ascii_binder/pull/110
