### ISSUE TITLE
Add hint how to create an AsciiBinder structure when you start from scratch

### ISSUE THREAD

**Issue by indigo423** [redhataccess/ascii_binder#109]
When you start from zero, the documentation does not tell you to create the project structure to get started. The directory `templates` is a good starting point.

**Comment by nhr** [comment]
I agree. The docs really need a rewrite. I'd like to restructure the docs like this:

1. Creating a new AsciiBinder-based docs repo from scratch
2. Super-basic use of AsciiBinder (1 distro, 1 branch)
3. Managing different versions of the docs in 1 repo
4. Managing different distros of the docs in 1 repo
5. Distributing AsciiBinder-based docs
    * As a website
    * (Eventually) as ePub / PDF

Interested to get your feedback on this.

**Comment by danyill** [comment]
:+1:
