### ISSUE TITLE
Support for internationalization

### ISSUE THREAD

**Issue by ciampix** [redhataccess/ascii_binder#112]
It would be great if ascii_binder supported internationalization. It could be done through the use of po4a that supports Asciidoc as already done by some people (see the [KiCad](http://kicad-pcb.org/) [documentation](http://kicad-pcb.org/help/documentation/))

**Comment by bexelbie** [comment]
I am working on this with AB and the Fedora Docs set.  I am looking at it as wrapping around AB initially so we can discover where it may make sense to integrate it.

This is a hugely WIP and terrible branch, but my current work is here:

https://pagure.io/fork/bex/fedora-docs/docs-fp-o/branch/multi-language-support

I will not be working on this for the next few weeks as I will be traveling, however if people want to help, I am happy to collaborate in November.  Right now the theory is to use a scripted set of po4a calls, and not use a po4a config.  This could be changed ...

**Comment by ciampix** [comment]
Well for a basic use of po4a for asciidoc I can pass you some examples I already used...

**Comment by bexelbie** [comment]
@ciampix I've activated the issue tracker for https://pagure.io/fork/bex/fedora-docs/docs-fp-o -- can you open an issue with your examples there?

**Comment by ciampix** [comment]
Sure, let me create an account first and collect some examples I have as Makefile...

**Comment by ciampix** [comment]
For the time being see this: https://github.com/KiCad/kicad-doc/blob/master/utils/old-build-scripts/Makefile it is for asciidoc but the po2a part should be the almost the same...
