### ISSUE TITLE
Homepage broken?

### ISSUE THREAD

**Issue by danyill** [redhataccess/ascii_binder#117]
Either something funny going on or http://www.asciibinder.org/ is down - DNS address unable to be found.

**Comment by danyill** [comment]
Oh I see. All the links I can find easily here go to the address with www in front of it.

Turns out probably this pointed at least at one stage to http://asciibinder.org/ which still exists. Either the web configuration needs to be fixed or the links updated.

**Comment by nhr** [comment]
I migrated to a new server. Sorry for the interrupted web service!
