### ISSUE TITLE
Release inconsistency

### ISSUE THREAD

**Issue by indigo423** [redhataccess/ascii_binder#130]
The Gem version is 0.1.14 and the latest release on GitHub is 0.1.12? Is the GitHub release page unmaintained and obsolete?

**Comment by bexelbie** [comment]
@nhr ?

**Comment by indigo423** [comment]
If you click on the repository on releases you see as latest release 0.1.12. When you go to the README of the project the gem version tag shows 0.1.14.

**Comment by nhr** [comment]
Sorry - this should be fixed now.
