### ISSUE TITLE
Community Video Call - Wed 17 Jan @ 2000 UTC

### ISSUE THREAD

**Issue by bexelbie** [redhataccess/ascii_binder#133]
Their will be a call to talk about the roadmap for AsciiBinder - potential topics include:

- Plans and Goals for the Project
    - Markdown support?
- Next Release Goals
- Next Meeting/Cadence

Feel free to add more topics in this issue.

The meeting will take place on meet.jitsi.com.  The meeting url will be posted before the call in this ticket.

Please consider subscribing to the ticket if you are interested in getting an email when the call url is posted.

**Comment by bexelbie** [comment]
I apologize for the late posting of this - the committers set the date a while back and I failed to get the information posted soon enough.

**Comment by bexelbie** [comment]
@nhr - how can I update the website with this?  I'll put a PR in momentarily.

**Comment by bexelbie** [comment]
CC: @indigo423 @r0ckarong @adellape @nigelbabu

**Comment by nhr** [comment]
@bexelbie I'll just manually build and publish for now. Let me know when you are ready for me to do that.

**Comment by indigo423** [comment]
Thank you for an invitation, try to get my schedule free for the community video call. Looking forward with greetings from Europe, Stuttgart.

**Comment by nigelbabu** [comment]
Blah, 1 am for me. But I'll catch up with @bexelbie afterward :)

**Comment by indigo423** [comment]
Did I missed something :)

**Comment by bexelbie** [comment]
@indigo423 not yet :) @nigelbabu was letting us know he can't be there as his timezone is not terribly conducive to attendance.  Call is in 1.25 hours from time on this comment.

**Comment by bexelbie** [comment]
The call url is https://meet.jit.si/AsciiBinder

**Comment by bexelbie** [comment]
Meeting Etherpad for minutes http://etherpad.osuosl.org/1rl56dEQ88

**Comment by indigo423** [comment]
Thank you for organizing this very constructive meeting.

**Comment by bexelbie** [comment]
I am putting the etherpad minutes here for preservation.  I am going to leave this open until the next meeting to reference the areas of focus here.  Ideally this will get converted into assignments and tasks in Github.

Areas of focus

- Search - ideally bex and indigo423 to work on this
  - With plain asciidoc there was a single page - now with multi-page we need to deal with search
  - There is the Gluster AB search plugin - but it suffers from usability perspective (our image for the Gluster AB search plugin: https://github.com/opennms-forge/docker-asciibinder-search)
    - can we some how solve search?
    - In the static CMS Hugo (http://gohugo.io) there is a quite smart JavaScript client side search functionality implemented. Probably we can leverage here. Here is an working live docs example from one of our tools I maintain: https://pris.opennms.eu. This is what the Hugo project is using for JavaScript and cliend side search: https://lunrjs.com
    - Openshift uses an homegrown option after Google Search went down
    - There are some other online options
    - A challenge is that a low impact static website from AB is made potentially very heavy by a search engine and java script may not (and so far has not) scaled well
    - We should leverage outside search solutions and not invent our own as much as possible
    - could we produce a google standard sitemap
    - we generate a sitemap in XML today that is google standard for google custom search so leverage this
    
- Goals from nhr to all of us (and we liked them) from his time as essentially sole maintainer
  - make subdirectory builds work - nhr to work on this
  - add easier image locations (fix some hard coded directories) - nhr to work on this

- Add generic vars support #126 - bex to work on this
  - Needs tests
  - No concerns raised on the call
  - It may gather some usage

- Add support for unlimited navigation templates - https://github.com/redhataccess/ascii_binder/pull/122 - bex to work on this
  - code comment: the code for AB supports arbitrary depth but is currently hard limited at depth of 2 because the templates currently do not support more
  - philosophy issues - other than concerns about encouraging bad deep docs, none

- Vikram going to triage the docs issues and resolve them

- Markdown - not going to push this for now
  - Markdown does not support ifdef for content conditionalization in a topic.  This means that we lose that functionality in markdown.  This could be reimplemented with pre_post processing or by using directories and doing duplicate content
  - This could also cause issues with "single doc html" and "pdf" generation from the repo
  - This means AB as a tool needs a similar markdown gem - this works for AsciiDoc but system calls or other challenges to call parsers could create scale problems
  - we need a way to not drag in unneeded dependencies for installations that don't need it
  - polling the call there is no requirement other than possibly from Fedora
  - a potential benefit of adding this enforces a separate of rendering engine from AB's work as a site builder
  - if this moves forward it needs to be rebased and get testing, including a test repo

Next Meeting in early March.  Normally we would do monthly meetings, but there is a Fedora Docs FAD at the end of February that will hopefully generate some code commits for AB.
