### ISSUE TITLE
Where to store our build infrastructure?

### ISSUE THREAD

**Issue by bexelbie** [redhataccess/ascii_binder#140]
We need to figure out where to store the ansible playbooks/roles that drive our automated hosting being provided by OSAS.  Should we create a new repo in this organization? Create our own org and migrate there and put a repo there? Store it with other playbooks in their repository?

@duck-rh can provide more details

**Comment by duck-rh** [comment]
Currently the current org is a bit of a mess and does not really help identify the community properly, so I would strongly suggest creating on and moving the code repo and other po4a-related repos there.

As for infra, it makes sense to create a new one with the Ansible deployment rules there too. I can set it up. It would allow to drag contributors more easily. Nevertheless po4a is a small community, so If no one is going to take care of it but me it would be simpler to keep the rules in the OSAS repo. So it depends if you of Harrison are going to give a hand, or work on building an infra community, or no time for that.

Whatever you choose is not final. We can transfer rules from one to the other; if we continue using the same roles it should be fairly easy.

**Comment by vikram-redhat** [comment]
Closing and cleaning up old issues.
