### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by jmferrer** [redhataccess/ascii_binder#147]
Hi,

I want to build an asciidoc based portal and I found asciibinder. I saw last commit was on Tue Mar 6 23:18:31 2018 .
I would like to know if this project will be continued or is dying.

Thank you

**Comment by nhr** [comment]
Hey @jmferrer -- this project is on life support. I encourage you to check out [Antora](https://antora.org) as it is functionally similar and has an active upstream community.

**Comment by jmferrer** [comment]
I did it and now I am part of that community.: https://github.com/elmanytas/openshift-antora-template

I tested awestrut, asciibinder and antora. I choose the antora way.
