### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by abellotti** [redhataccess/ascii_binder#15]
First, not sure if it's styling choice or not, for document menus, when expanding topic groups and such, there are no icons like > to expand and ^ to contract the topic menus.

Second, the admonition icons (info, warning, etc.) seem to be missing, I get the blue square instead.

**Comment by nhr** [comment]
Good call. I lifted most of the default template our of what was done for OpenShift but clearly there are some broken paths, or possibly missing glyphs.

The page nav element glyphs are supposed to be coming from Bootstrap. The admonition icons should be coming from Asciidoctor.

**Comment by Fryguy** [comment]
Closed by #16
