### ISSUE TITLE
asciibinder.org site offline/overtaken

### ISSUE THREAD

**Issue by cstuder** [redhataccess/ascii_binder#154]
http://asciibinder.org seems to have been overtaken by a domain squatter/spammer.

**Comment by cstuder** [comment]
FYI: Last version of the documentation in the wayback machine can be found here: https://web.archive.org/web/20190718011419/http://asciibinder.org/latest/welcome/

**Comment by vikram-redhat** [comment]
Hi @cstuder - yes we are only maintaining it minimally now. I a hoping that there are no links in the wild to that site anymore.

**Comment by nhr** [comment]
FWIW, I've relaunched the site on https://asciibinder.net/ but per @vikram-redhat the project is in cruise control unless someone steps in to drive new development.
