### ISSUE TITLE
documentation command issue

### ISSUE THREAD

**Issue by MohdIzhar** [redhataccess/ascii_binder#155]
minishift --profile profile-demo minishift start
Error: unknown command "minishift" for "minishift"
Run 'minishift --help' for usage.
unknown command "minishift" for "minishift"
The command mentioned in documentation https://docs.okd.io/3.11/minishift/using/profiles.html

**Comment by nhr** [comment]
This should be opened as a bug against OKD / OpenShift documentation, not the generator tool. You can find the OpenShift docs source at: https://github.com/openshift/openshift-docs
