### ISSUE TITLE
Support for epub format

### ISSUE THREAD

**Issue by mnagy** [redhataccess/ascii_binder#18]
It would be great if ascii_binder supported epub format. I'd love to read docs on my reader :)

**Comment by php-coder** [comment]
... and PDF too :)

**Comment by nhr** [comment]
Both of these require the utility to combine all of the topics into a single document with a TOC that links to each topic with the document. We also need to add templates & style sheets for each format. Finally we'll need to add an output format option to the CLI.

**Comment by mnagy** [comment]
What are the challenges? Any way I can help?

**Comment by nhr** [comment]
Thanks for the offer, but the work is pretty straightforward. I just wanted to describe the scope for when I come back around to implementing it.

**Comment by bexelbie** [comment]
This could also be used to generate single-page.html.

Can you share implementation details in case I have time to work on it?
