### ISSUE TITLE
a docker hub image would be nice

### ISSUE THREAD

**Issue by ReSearchITEng** [redhataccess/ascii_binder#21]
Even if it's easy to install, it would be nice to have an docker image on dockerhub

**Comment by nhr** [comment]
Good call!

**Comment by nhr** [comment]
Ask, and ye shall receive: https://hub.docker.com/r/projectatomic/ascii_binder/
This is built with the included [Dockerfile](https://github.com/redhataccess/ascii_binder/blob/master/Dockerfile)

**Comment by ReSearchITEng** [comment]
Great, super great. Thank you!
