### ISSUE TITLE
Add branch specific option(s)

### ISSUE THREAD

**Issue by adellape** [redhataccess/ascii_binder#22]
Similar to the `-d` / `--distro` option, add a `-b` / `--branch` option to specify only building given branches. This would enable speedier local testing.

Personally, I'd probably also prefer if a vanilla `asciibinder build` defaulted to building all distros for only the current working branch (all pages), though I'm not sure whether that would require altering of any of the docs.openshift.* site build jobs as a result. If implemented, possibly also a `--all-branches` to mimic the current default behavior? If not implemented, then maybe instead a flag to indicate "just build the current working branch, all pages, all distros".

**Comment by tnguyen-rh** [comment]
Thumbs up for speedier local testing.  I don't mind keeping the "heavy" `build` behavior as default if `--branch` is implemented, however.  (Personally, in that case, i would create and use an alias for `build --branch` and never use naked `build`.)

**Comment by adellape** [comment]
Yeah, fair enough.

**Comment by Fryguy** [comment]
Closed in #35
