### ISSUE TITLE
Make page path of current page/topic available as a variable

### ISSUE THREAD

**Issue by luciddreamz** [redhataccess/ascii_binder#26]
The path of the current page should be accessible as a variable on all pages and within the site template. This would allow us to add a canonical tag to the site header to indicate the full URL of the page that search engines should index.

For example, in Awestruct I can create the canonical tag using the [`site.base_url` and `page.url`](http://awestruct.org/template_context/) root object properties as follows:

    <link rel="canonical" "<%= "#{site.base_url}/#{page.url}" %>">

With AsciiBinder, I would imagine being able to reference the current page path with a `topic_path` variable as follows:

    <link rel="canonical" "<%= "#{site_url}/#{topic_path}" %>">

The `topic_path` name feels consistent with [other AsciiBinder variable naming conventions](http://www.asciibinder.org/latest/guides/maintainer_guide.html#styling-your-docs).

**Comment by nhr** [comment]
Reviewed, will implement.
