### ISSUE TITLE
command to dump document structure

### ISSUE THREAD

**Issue by tnguyen-rh** [redhataccess/ascii_binder#28]
To maintain revision histories, we need to correlate a change in a specific file with its public id (i.e., the 2-tuple `HEADER-LINE`, `SPECIFIC-ID`).  It would be nice if Asciibinder could dump out the document's structure in a machine-readable format.  Something similar in content to:

```
$ find . -name '*.adoc' | xargs grep -E -nH -e '(^=+ )|(^\[\[.+\]\])'
./rest_api/revhistory_rest_api.adoc:1:= Revision History: REST API Reference
./rest_api/openshift_v1.adoc:1:= OpenShift v1 REST API
./rest_api/openshift_v1.adoc:12:== Overview
./rest_api/openshift_v1.adoc:15:=== Version information
./rest_api/openshift_v1.adoc:18:=== URI scheme
[...]
./whats_new/ose_3_0_release_notes.adoc:1:= OpenShift Enterprise 3.0 Release Notes
./whats_new/ose_3_0_release_notes.adoc:13:== Overview
./whats_new/ose_3_0_release_notes.adoc:28:== New Features
./whats_new/ose_3_0_release_notes.adoc:53:== Installing OpenShift Enterprise 3.0
./whats_new/ose_3_0_release_notes.adoc:58:== Migrating Applications to OpenShift Enterprise 3.0
./whats_new/ose_3_0_release_notes.adoc:63:[[technology-preview]]
./whats_new/ose_3_0_release_notes.adoc:64:== Technology Preview Features
./whats_new/ose_3_0_release_notes.adoc:92:== Known Issues
./whats_new/ose_3_0_release_notes.adoc:101:== xPaaS Images
./whats_new/ose_3_0_release_notes.adoc:111:=== xPaaS Image for Red Hat JBoss EAP
./whats_new/ose_3_0_release_notes.adoc:128:[[jboss-eap-6.4-v1.1.0]]
[...]
```

but in proper order (as specified by `_build_cfg.yml`) and respecting the conditionals (i.e., `ifdef::` directives).  Actually, whether the default output format is machine-readable or human-friendly is unimportant; it's enough to provide an option to select the preferred format.  If you're at a loss for a name for this command, i suggest `dump-structure`.

**Comment by nhr** [comment]
Help me understand the function of (working title) `dump-structure`.

If I run `asciibinder dump-structure` in the root of an AsciiBinder-aware docs repo, what is the output?

You mentioned ifdefs, so presumably `dump-structure` would need to accept a distro-tag as an argument.

I think you want to see a tree-like output, something like:

```
Topic Group 1 Title
|- Topic 1 Title
|    |- Heading 1.1
|    |- Heading 1.2
|    |    |- Subheading 1.2.1
|    |    |- Subheading 1.2.2
|    \- Heading 1.3
|- Topic 2 Title
|    |- Heading 2.1
...etc
```

For the current branch and distro. Is that correct or am I missing something?

**Comment by tnguyen-rh** [comment]
Re distro tag -- yes that needs to be specified.

Re output -- Tree-like would be great for humans.  For machines, the output should be regular (for easy parsing by other tools), and include section title, section numbering, section id, file name and line numbers.  The idea is to make it easy (and mechanical, via another tool) to look at `git diff` output, correlate the file name and line number information there with a specific section, and construct a relative URI to that section (or next-level-up enclosing linkable unit should no section id be available).

**Comment by nhr** [comment]
What machine / utility needs to process this, and what does it do with that information? I think I am missing a piece of the workflow that would provide context for this feature.

**Comment by tnguyen-rh** [comment]
The utility is not yet written, although the general functionality of the utility is sketched in the the `post-commit` script posted to the `openshift-docs` mailing list (thread "Weekly Publishing 15/Feb").  The manual process this utility is trying to automate is documented in step 6 of [How To Publish To Downstream OpenShift Branches](https://mojo.redhat.com/docs/DOC-1047872).

**Comment by Fryguy** [comment]
Isn't YAML a machine readable format?

**Comment by tnguyen-rh** [comment]
@Fryguy
Yes, it is.

The top-level file `_build_cfg.yml` contains part (most) of the structural information.   Other structural info manifests as `include::` directives and `ifdef::` (conditional) blocks.  The effective (rendered) structure requires grokking all of the above.  This is what Asciibinder does, so this RFE is basically asking for that post-grokking structure to be shared in some convenient format (rather than reinvent, perhaps in subtly incompatible ways, the grokking logic).
