### ISSUE TITLE
"changelog" topic organization record support

### ISSUE THREAD

**Issue by nhr** [redhataccess/ascii_binder#30]
_Note that the changelog concept is under active discussion and so this is currently just an advisory issue._

This is a two-part proposal. Part one is for a changelog format that provides a history of topic file moves / renames / deletes within a single repo. Part two is for additional AsciiBinder features that would make it easy for writers to move / rename / delete topics and have AsciiBinder automatically modify the `_build_cfg.yml` and `_changelog` files accordingly.

The two primary benefits of change tracking are as follows:
1. For the benefit of teams that use AsciiBinder to publish their documentation sets as HTML, AsciiBinder could use the changelog to generate HTTP redirect rules automatically.
2. For the benefit of others that want to reuse content from a documentation repo, the changelog can be inspected to inform those consumers of docs reorganization events.
## Proposal: changelog File Format

Scenario: a topic at path “coolconcept/explanation.adoc” gets renamed to “coolconcept/user_guide.adoc” and later is reorganized under “howtos/“. At some point after that, the file gets split up into new topics and the original file is deleted entirely.

Here’s what the changelog file might look like:

```
2014-01-01 coolconcept/explanation.adoc => coolconcept/user_guide.adoc
2015-08-25 coolconcept/user_guide.adoc => howtos/user_guide.adoc
2016-02-17 howtos/user_guide.adoc => [deleted]
```

The general form is:

```
YYYY-MM-DD <original_topic_group>/<topic_filename> => <new_topic_group>/<topic_filename>
```

The special token `[deleted]` can be used in place of a new group/topic path when a file is removed.
### Naming

In following the pattern of metadata naming in AsciiBinder repos, this file would be called `_changelog`.
### Maintenance

Over the lifespan of a docs repo, the changelog file runs the risk of getting very large. Currently a pruning delta of one year seems reasonable. In other words, as the oldest changes in the file exceed a year in age, they could be removed from the changelog.
## Proposal: AsciiBinder Topic Management Functions

AsciiBinder can be extended with a few new functions to simplify the use of the changelog.
### move-topic [source_path] [target_path]

This function would do the following things on behalf of the user:
1. `git mv` the topic file
2. update the `_changelog` file
3. update the `_build_cfg.yml` file
### delete-topic [topic_path]

Similar to move-topic this would:
1. `git rm` the topic file
2. update the `_changelog` file
3. update the `_build_cfg.yml` file
### publish

This function already exists, but based on the presence of the `_changelog` file it could generate a set of redirect rules suitable for use in Apache or NGINX.

**Comment by nhr** [comment]
Note that the changelog concept is under active discussion and so this is currently just an advisory issue.

**Comment by Fryguy** [comment]
I like the changelog idea in general, but think it should be named something different like movelog or redirectlog .  I'm concern it can be confusing with project changelogs.

**Comment by mattdm** [comment]
I'd like to +1 this request for Fedora documentation. As we are organically building up our docs site, it often turns out that we put something where it doesn't best belong. It'd be awesome to have asciibinder keep track of and create the needed redirects.

**Comment by nhr** [comment]
Independent of this feature set, AsciiBinder is capable of creating redirect stubs now. If you add an 'Alias' value to a topic in the _topic_map file, you transform that topic into a redirect to whatever the value of the 'Alias' is.

**Comment by mattdm** [comment]
Hmmm. Ok. "Alias" might work, but is very ugly for something like this, where I want to say "Rearranged", not "Alias".

**Comment by mattdm** [comment]
@nhr (But thanks -- I can use that for now!)

**Comment by nhr** [comment]
Alias functionality definitely doesn't satisfy the requirements of this feature, but now that Alias functionality exists, it will be used by this feature to accomplish the changelog-based redirections.
