### ISSUE TITLE
Proposal: Rename _build_cfg.yml to _topic_map.yml

### ISSUE THREAD

**Issue by nhr** [redhataccess/ascii_binder#31]
As AsciiBinder has evolved, the function of _build_cfg.yml has evolved as well. At this point, the name is not particularly helpful in communicating what the purpose of the file is. "_topic_map.yml" would be more consistent with "_distro_map.yml" and would help to illustrate how those two files differ but interrelate.

@Fryguy - thoughts?

**Comment by adellape** [comment]
+1

**Comment by Fryguy** [comment]
:+1:  One suggestion is to deprecate in one version and remove in the next.

**Comment by nhr** [comment]
Reviewed. Will be implemented.
