### ISSUE TITLE
Enable per-site-ID template directories

### ISSUE THREAD

**Issue by nhr** [redhataccess/ascii_binder#34]
Presently AsciiBinder supports a single page template folder `_templates` in a docs repo. This is not as flexible as it could be for handling different page layouts on a per-site basis.

What I would like to propose is this:

Under the `_templates` directory, there should be one or more per-site directories. One of these must be called `default`, and this directory is the template directory used by all sites by default. However, other directories _may_ exist in the `_templates` directory. If these directory names correspond to a `site:` value in `_distro_map.yml`, then AsciiBinder will use the templates in that directory to render the topics and topic groups for that site.

In order to support currently established docs repos, this enhancement must be backward compatible.

Therefore:

* A `_templates` directory with no child directories is handled exactly like `_templates/default` under the new behavior. This supports the existing cases.
* A `_templates` directory with one or more child directories will:
    * Never read template files stored in the `_templates` directory itself
    * Raise an error if one of the directories is not called `default`

This enhancement will make it much easier to support docs repos that are used as the source for more than two distinct websites.

@Fryguy , @adellape , @aweiteka please review and comment

**Comment by adellape** [comment]
Seems fine to me!

**Comment by nhr** [comment]
This is in reference to https://github.com/openshift/openshift-docs/pull/1698

**Comment by nhr** [comment]
@Fryguy talked me out of this in favor of conditionalizing the templates by levaraging existing ERB functionality. I'm going to close this out for now.
