### ISSUE TITLE
:data-uri: must be used to embed images, otherwise images don't work

### ISSUE THREAD

**Issue by lnewson** [redhataccess/ascii_binder#44]
When trying to use images in AsciiBinder without embedding them via the :data-uri: attribute, images don't work as soon as you move them to another host. I had a bit of a look into it and the cause looked to be because of:
1) AsciiBinder overrides the :imagesdir: attribute to point to the source images absolute path (ie /home/bne/lnewson/tmp/git/openshift-docs/getting_started/images/copy.jpg). This should really be either a) a relative path passed or b) should let the user define where the images are using the :imagesdir: attribute.
2) AsciiBinder doesn't copy images into the site build, so it won't work unless you embed them. If AsciiBinder expects images to be embedded, then it should be setting the :data-uri: attribute instead of relying on authors to add it.

Related: https://github.com/openshift/openshift-docs/pull/2134

**Comment by nhr** [comment]
This has been fixed; closing.
