### ISSUE TITLE
First line gets rendered as the title

### ISSUE THREAD

**Issue by lnewson** [redhataccess/ascii_binder#45]
If you try and set an ID on the header (which is the initial title when included), then the ID gets rendered instead of the title. eg:
```
[[my-section]]
= My Section Title
```

The first line in a file is rendered as the title, this means that you cannot set an ID to use in an xref and therefore you cannot link to that without using the title in the xref or linking to the output format filename, which makes it impossible to use in included (include::) or pretty much outside AsciiBinder. This looks to be caused by the following line in helpers.rb, because it assuming the title will always be on the first line.
```
article_title  = file_lines[0].gsub(/^\=\s+/, '').gsub(/\s+$/, '').gsub(/\{product-title\}/, distro_config["name"]).gsub(/\{product-version\}/, branch_config["name"])
```

This is incorrect as it might have the ID, front matter[1] or other items that make it so the title isn't on the first line. So it should instead either get the title in some other fashion, or search for it. Just as a reminder titles can be defined in different ways in AsciiDoc, eg:
```
= My Title
```
```
My Title
========
```
or even markdown style headings (this is AsciiDoctor specific though)
```
# My Title
```

[1] http://asciidoctor.org/docs/user-manual/#static-website-generators

**Comment by lnewson** [comment]
Can't say I've tried it but based on the docs[1] looks like you could get the title by parsing it and getting the title from the doctitle attribute. ie
```
doc = Asciidoctor.load topic_adoc, :header_footer => false, :safe => :unsafe, :attributes => page_attrs
article_title = doc.doctitle.
```

[1] http://asciidoctor.org/docs/user-manual/#load-and-render-a-file-using-the-api

**Comment by lnewson** [comment]
Also found that you can't use inline id's[1] in the title/header to try and workaround this because they are rendered as well. ie:
```
= [[my-section]]My Section Title
```

At this stage the only workaround that we've come up with is to use an ID below the title/above the toc. That way it'll link just below the title, but that's not optimal.

[1] http://asciidoctor.org/docs/user-manual/#anchordef

**Comment by Fryguy** [comment]
Thanks @lnewson for the report.  I noticed something similar as well, and couldn't understand what was going on.  Our workaround in our docs was to put a blank line at the start but I never liked that hack.

**Comment by nhr** [comment]
This has been fixed; clsoing.
