### ISSUE TITLE
How to add Fonts to package?

### ISSUE THREAD

**Issue by r0ckarong** [redhataccess/ascii_binder#51]
How can I add custom fonts to the packaged documents? I need to package my stuff for deployment in locations that are not connected to the internet for security reasons but want to preserve the Corporate Identity. Can I somehow create a _fonts directory that will automatically be copied over?

**Comment by Vinzz** [comment]
I'd also be interested in such a feature,

thanks

**Comment by r0ckarong** [comment]
Added PR #66 to resolve this.
