### ISSUE TITLE
Need ability to fail a build if _topic_map.yml is not updated

### ISSUE THREAD

**Issue by Fryguy** [redhataccess/ascii_binder#52]
In the manageiq_docs repo, I've created a simple test suite that just runs `asciibinder build`. See https://github.com/ManageIQ/manageiq_docs/pull/61.  I have this running via Travis so that when doc writers make a PR to update the docs, it should fail if they do something wrong.  However, I can't figure out how `asciibinder build` would ever fail.

I'm thinking that maybe there could be an `asciibinder check` command or perhaps `asciibinder build --check` that would fail and `exit 1` if some conditions aren't met.  The only thing I can think of offhand are the current WARNING messages about not updating the _topic_map.yml could instead raise exceptions in this mode.  @nhr perhaps you or the openshift-docs team can think of more things?

**Comment by Fryguy** [comment]
Also, here's an example of what a run on travis looks like: https://travis-ci.org/ManageIQ/manageiq_docs/builds/147576735

Of note in there are the vendor files that should probably be ignored anyway.

**Comment by bexelbie** [comment]
#57 and #58 address the _vendor files if you make that move.

I don't like this idea though, as I believe there are good reasons for there to be unincluded files.  As an example, the Fedora Docs, which I am pushing for using asciibinder, have some files that are included in Preface.adoc but maintained as common_content in a separate repo.  Those files will always appear in place, but never be referenced directly in _topic_map.yml

I wonder if you should solve this solely with travis somehow.  I would look to see if you can determine what files were added or deleted in the commit.  If any of them are .adoc files in your source directories you could either verify that _topic_map.yml was updated too or that it contains the files that were changed.  This would still fail for cases where you have an included file, but those could be cases where you ignore this tests output.
