### ISSUE TITLE
imagesdir attribute in document is ignored

### ISSUE THREAD

**Issue by r0ckarong** [redhataccess/ascii_binder#53]
I tried to add images in a folder not named "images" and I referenced it according to the Asciidoctor guidelines but in the output the images can not be found. My structure looks somewhat like this:

```
folder-img:
  image.png
  image2.png
document.adoc
```

The document has:

```
= Title
:toc:
:imagesdir: folder-img

<<<

== Introduction
Some text

image:{imagesdir}/image.png
```

In Asciidoc preview this works but not in Asciibinder output.

**Comment by nhr** [comment]
AsciiBinder hard-codes the `imagesdir` value to only look for an `images` directory:
https://github.com/redhataccess/ascii_binder/blob/master/lib/ascii_binder/helpers.rb#L756

Enforcing the dirname makes identifying and cleaning up DITAA-generated images _much_ easier, but I'm open to suggestions on a better way to address this.

**Comment by r0ckarong** [comment]
A start would be to document this limitation in the official docs. Not knowing this made it quite hard for me to undertand why images wouldn't show up. Then I had to experiment which (by the "commit everything before you try" nature of AsciiBinder) was really tedious.

**Comment by r0ckarong** [comment]
This now leads to another interesting behavior. 

You have a document using images. Then you include that document in a different place. Then the images are not resolved from the original location but relative to where the document lies.

Is this intentional? If I can not declare the imagesdir argument I must have duplicates of the images in two locations which is really not very efficient.

```
images/
  image1.png
Document.adoc

Document2.adoc
```

When you include Document.adoc in Document2.adoc images do not work in the exported pages.

**Comment by nhr** [comment]
To me, this is an argument for centralizing the image location in the repo, which simplifies reuse of images and makes them immune to `include::` related issues. We already take a similar approach to `include::` macros themselves. Would it be reasonable to you if we required all images to go into a single directory in the root dir of the repo? Thoughts, @Fryguy and @adellape ?

**Comment by adellape** [comment]
> Would it be reasonable to you if we required all images to go into a single directory in the root dir of the repo?

@nhr I like this, as I've had to do the described "duplicates of the images in two locations" workaround previously.

**Comment by Fryguy** [comment]
I have no personal opinion on the matter... I kind of like being able to specify whatever I want versus forcing the user into a specific directory, then using either absolute or relative paths.

I think however that forcing images into a root directory will break the current manageiq_docs, so I'd like @adahms'  opinion.

**Comment by adahms** [comment]
@Fryguy - Thank you for the callout.

Moving all images into a single directory in the top level of the repository is something we have been discussing, and I think this would be a positive move in the long term for the documentation. As long as we coordinate on when the change needs to be made, it shouldn't be too difficult for us to implement.

In it's current state, however, making this change without preparing the documentation for it could cause some unexpected side effects, so we would need a little time to check that everything can go ahead smoothly.

**Comment by nicorikken** [comment]
Forcing existing documentation to move all images to a `_images` folder increases the migration burden. It seems like a sensible default though. I consider a flag to respect `imagesdir` locations a way to go about this.

@nhr regarding the DITAA images: [asciidoctor-diagram](https://github.com/asciidoctor/asciidoctor-diagram) is able to handle the `imagesdir` attribute. Perhaps it makes sense to build support for this extension, rather than building your own image-generation toolchain?

**Comment by bexelbie** [comment]
I am also opposed to enforced centralization.  I think if we want to support a central repository, it should be allowed, probably through a command line option.  I believe that option could also turn off the imagedir allowing arbitrary statements in the text.

However, I would like to see the default behavior remain.  It works well and it meets a use case I have for non data-uri supporting formats.
