### ISSUE TITLE
Ruby "rescue in merge" error in build, success anyway

### ISSUE THREAD

**Issue by r0ckarong** [redhataccess/ascii_binder#55]
We have split our documentation into two separate branches and want to build a specific one with a jenkins job. We get this error at the end of the build which completes successfully nonetheless.

Can you help me debug the problem here? I have attached the document that apparently throws the error. (Renamed from .adoc because of GitHub upload policy)
[curl-examples.txt](https://github.com/redhataccess/ascii_binder/files/435044/curl-examples.txt)

```
[...]
  - developer/curl-examples
/usr/lib/ruby/2.3.0/uri/generic.rb:1102:in `rescue in merge': both URI are relative (URI::BadURIError)
	from /usr/lib/ruby/2.3.0/uri/generic.rb:1099:in `merge'
	from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:89:in `each'
	from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:89:in `inject'
	from /usr/lib/ruby/2.3.0/uri/rfc3986_parser.rb:89:in `join'
	from /usr/lib/ruby/2.3.0/uri/common.rb:265:in `join'
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator/sitemap_location.rb:85:in `url'
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator/builder/sitemap_index_file.rb:143:in `write_first_sitemap'
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator/builder/sitemap_index_file.rb:104:in `finalize!'
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator/link_set.rb:461:in `finalize_sitemap_index!'
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator/link_set.rb:334:in `finalize!'
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator/link_set.rb:41:in `create'
	from /var/lib/gems/2.3.0/gems/sitemap_generator-5.1.0/lib/sitemap_generator.rb:42:in `method_missing'
	from /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:839:in `block (2 levels) in package_docs'
	from /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:806:in `each'
	from /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:806:in `block in package_docs'
	from /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:804:in `each'
	from /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/lib/ascii_binder/helpers.rb:804:in `package_docs'
	from /var/lib/gems/2.3.0/gems/ascii_binder-0.1.4/bin/asciibinder:296:in `<top (required)>'
	from /usr/local/bin/asciibinder:23:in `load'
	from /usr/local/bin/asciibinder:23:in `<main>'

All builds completed.
```

**Comment by nhr** [comment]
This error is coming from our attempt to create a sitemap XML file at the end of the processing run. We use a Ruby gem called SitemapGenerator to do this. Looking at issues on SitemapGenerator, I found this which look relevant: https://github.com/kjvarga/sitemap_generator/issues/230

We set the `default_host` property for SitemapGenerator from the `site_url` property of each distro in your `_distro_map.yml` file. Make sure you use a valid value that includes the protocol, like so: https://github.com/openshift/openshift-docs/blob/master/_distro_map.yml#L7

**Comment by r0ckarong** [comment]
I stumbled upon that solution in the mean time, forgot to close this here. One of my colleagues didn't quite grasp the site_url parameter and put a slash as a placeholder which disagreed with the script. We're not going to do this anymore ;)
