### ISSUE TITLE
Can all underscore led files and directories be ignored?

### ISSUE THREAD

**Issue by bexelbie** [redhataccess/ascii_binder#57]
If I create a directory of unpublished material called _foo can it get ignored for reporting unpublished files purposes?

**Comment by nhr** [comment]
Great idea. I have to do an update to add a separate feature, but I can include this in the PR. Pinging @Fryguy for context.

**Comment by bexelbie** [comment]
I went ahead and gave it a shot ... feel free to close if it fits more logically in your PR.
