### ISSUE TITLE
Why do we have repo-root based include file handling?

### ISSUE THREAD

**Issue by bexelbie** [redhataccess/ascii_binder#60]
Much like the handling of images, AsciiDoctor forces an unexpected (at least by me) file management thought process on the user.  Why do we do that?

Today, AsciiDoctor roots all file includes at the repository's root directory.  For example, if I have this file structure (just docs):

```
.
├── docs
│   ├── a.adoc
│   ├── b.adoc
│   └── more_docs
│       └── c.adoc
├── global.adoc
```

If I want the file `a.adoc' to  include the files`b.adoc`,`c.adoc`and`global.adoc`, I have to write the following:

```
include::docs/b.adoc[]
include::docs/more_docs/c.adoc[]
include::global.adoc[]
```

This seems less logical in most cases and you would expect the local directory to be the point of resolution.  In other words, I would expect to write:

```
include::b.adoc[]
include::more_docs/c.adoc[]
include::../global.adoc[]
```

Using `Asciidoctor.load_file` would make this instead of first reading in the file to a string and using `Asciidoctor.load`.  See: 
https://github.com/redhataccess/ascii_binder/blob/master/lib/ascii_binder/helpers.rb#L765

Why was this decision made?

**Comment by nhr** [comment]
The main problem is documentation lifespan, and migration of topics over time. Your example `include::` invocation make sense if your topic file never moves. However, once it does, you will have to refactor all of those macros with the updated paths. By enforcing absolute paths for these, AsciiBinder ensures that you can move your topic anywhere in your docs and your `include::` statements will still be relevant.

**Comment by bexelbie** [comment]
If we bias toward topic reorganization then we need to do a much better job documenting this behavior and the rationale, imho.

I also wonder why we don't allow topic_map nesting without a physical directory?

**Comment by nhr** [comment]
Totally agree that the docs need improvement. I have some time that I can devote to this.

The coupling of the topic map to the actual structure is an accountability measure. We originally talked about holding all of the topic files in a single dir and using the topic map to organize them, but it is much saner to require these to match up. For instance, the [OpenShift docs repo](https://github.com/openshift/openshift-docs) has 200+ topics in it, and if the directory organization didn't match up with the topic map, the various upstream contributors would have a really hard time trying to find the specific files they actually want to contribute to.

**Comment by bexelbie** [comment]
I agree that it makes docs saner.  It would be nice if it was optional though.  Again, I am trying to coordinate an upstream-downstream sharing across toolsets.  I understand if the project doesn't wish to deviate though.  Just trying to examine my options.

**Comment by r0ckarong** [comment]
I'm interested in this topic too, this decision keeps me from maintaining one set of documents that I can easily export to PDF with asciidoctor-pdf. Since the include structure is specific to asciibinder it means I must maintain basically a complete copy of the documents that have "working" include directives and different structure.

**Comment by nhr** [comment]
@r0ckarong - I would rather solve that problem by enabling AsciiBinder to combine all topics into a single doc and then invoke asciidoctor-pdf enternally to produce a "bound volume" PDF of all topics with a meaningful TOC.

**Comment by r0ckarong** [comment]
@nhr Are there any concrete plans to implement this "one PDF" feature in the near future? Some of my users are asking for PDF output and I'm looking into various solutions to provide this. For now Asciibinder works well for the HTML portion but I would rather avoid implementing tooling for PDF publishing if this is coming soon anyway.

**Comment by nhr** [comment]
@r0ckarong I have a branch going that tackles the first part of the problem, which is simply the act of composing all topics into a single document: https://github.com/nhr/ascii_binder/tree/single_output_support

What I am sorely lacking right now are strong Ruby coders who can do code reviews. My project partner is seriously over-subscribed on regular work right now, so PRs can't be iterated upon.

**Comment by hferentschik** [comment]
I am also experiencing problems with file includes.
