### ISSUE TITLE
ascii_binder bin file is busted in 0.1.5 release

### ISSUE THREAD

**Issue by Fryguy** [redhataccess/ascii_binder#64]
In the repo, it's just a symlink, but in the 0.1.5 release the symlink is broken.  In manageiq_docs we have a rake task that runs using the ascii_binder symlink and that rake task is broken.

@nhr How did you create the release?

**Comment by nhr** [comment]
I ran `bundle exec rake release`.

**Comment by nhr** [comment]
Is it possible that this line is not grabbing the symlink?
https://github.com/redhataccess/ascii_binder/blob/master/ascii_binder.gemspec#L17

**Comment by nhr** [comment]
I see the problem. The symlink is broken in the gemfile. It ends up pointing to `$GEM_DIR/asciibinder` instead of `$GEM_DIR/bin/asciibinder`

**Comment by nhr** [comment]
This seems relevant: https://github.com/rubygems/rubygems/issues/1577
