### ISSUE TITLE
Nav toggle doesn't work

### ISSUE THREAD

**Issue by donnydavis** [redhataccess/ascii_binder#72]
The nav toggle doesn't work at all, even on the project site http://www.asciibinder.org/latest/welcome/

**Comment by donnydavis** [comment]
A workaround for the issue is to download this to the _javascripts folder
https://github.com/openshift/openshift-docs/blob/master/_javascripts/bootstrap-offcanvas.js

and then add this to the page.html.erb
<script src="<%= File.join(javascripts_path, "bootstrap-offcanvas.js") %>" type="text/javascript"></script>

**Comment by nhr** [comment]
Merged https://github.com/redhataccess/ascii_binder/pull/73 and https://github.com/redhataccess/ascii_binder/pull/74. Will bump version and publish the fix. Thanks for the contribution!
