### ISSUE TITLE
Problem with `watch`: undefined method `start_with?' for #<Pathname:welcome/index.adoc>

### ISSUE THREAD

**Issue by nhr** [redhataccess/ascii_binder#86]
Opening this on behalf of [this thread](https://groups.google.com/d/msgid/asciibinder/b5d5f914-f072-4532-ab65-c3e00be408c5%40googlegroups.com?utm_medium=email&utm_source=footer).

> I create a repo build it and then I run watch. And I  always get this exception for any changes in `welcome/index.adoc`. Any idea what I am  doing wrong ? 

```
asciibinder watch
10:24:41 - INFO - Using Guardfile at /home/nmajorov/.gem/ruby/gems/ascii_binder-0.1.9/Guardfile.
WARN: Unresolved specs during Gem::Specification.reset:
     ffi (>= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
10:24:41 - INFO - LiveReload is waiting for a browser to connect.
10:24:41 - INFO - Guard is now watching at '/home/nmajorov/workspace/missions/Ringer/report/report_binder'
[1] guard(main)> 10:24:41 - INFO - Browser connected.
10:24:57 - ERROR - Problem with watch action!
> [#] undefined method `start_with?' for #<Pathname:welcome/index.adoc>                                                                                                            
10:24:57 - ERROR - (eval):3:in `block (2 levels) in evaluate'
> [#] /home/nmajorov/.gem/ruby/gems/guard-2.14.1/lib/guard/watcher.rb:75:in `call_action'                                                                                          
> [#] /home/nmajorov/.gem/ruby/gems/guard-2.14.1/lib/guard/watcher.rb:44:in `block (2 levels) in match_files'                                                                      
> [#] /home/nmajorov/.gem/ruby/gems/guard-2.14.1/lib/guard/watcher.rb:39:in `each'                                                                                                 
> [#] /home/nmajorov/.gem/ruby/gems/guard-2.14.1/lib/guard/watcher.rb:39:in `block in match_files'
```

**Comment by Fryguy** [comment]
@nhr Did something change to a Pathname object recently?

**Comment by nhr** [comment]
I am not hitting this problem on Ruby 2.4.1. I've asked the submitter to get back to me with the version of Ruby they are using.

**Comment by Fryguy** [comment]
@nhr I see they're using ascii_binder 0.1.9, but I don't see the tags in this repo...can you push the tags to the repo, so I can see which commits went into which build?  (on that note are you using `bundle exec rake release`?)

**Comment by nhr** [comment]
I haven't tagged or published the new code; I was hoping to get in one more PR with some improvements to how we work with Git first. But if you think it is a good idea I'd be happy to cut a new version.

**Comment by Fryguy** [comment]
What I meant was that we are up to ascii_binder 0.1.9, but the git tags only go up to 0.1.6 (thus, 0.1.7, 0.1.8, and 0.1.9 tags are missing in git)

**Comment by nhr** [comment]
Got it! I've pushed them now.

**Comment by nmajorov** [comment]
Sorry to coming to the ticket after a long period, but it work  with latest version of asciibinder 
just start to play with it  again... :)

**Comment by nhr** [comment]
Awesome, thanks for letting us know!
