### ISSUE TITLE
Wrong placement of bootstrap-offcanvas.js in page.html.erb

### ISSUE THREAD

**Issue by pbaris** [redhataccess/ascii_binder#88]
After create a repo with command

`asciibinder create mydocs`

the file _templates/page.html.erb includes bootstrap-offcanvas.js in the head, but this script requires jQuery, which is loaded at the end of the body. So there is an js error an offcanvas does not work

The bootstrap-offcanvas.js script should be loaded at the body after the jquery.js

**Comment by nhr** [comment]
Thanks for providing a fix in https://github.com/redhataccess/ascii_binder/pull/89
