### ISSUE TITLE
clarification on philosophy page

### ISSUE THREAD

**Issue by tnguyen-rh** [redhataccess/ascii_binder#9]
Hi AsciiBinder hackers,

On the [philosophy page](http://www.asciibinder.org/latest/welcome/philosophy.html), there is the sentence: "AsciiBinder takes advantage of git pull requests as a means of refining content before it becomes part of the docs, ...".

What does that mean, precisely?  Is there any actual integration with GitHub?

**Comment by nhr** [comment]
There is no actual mechanical linkage here. Another way of saying the above is that by choosing git, AsciiBinder inherits git-centric contribution review patterns like pull requests. This would be in contrast to the sort of change review process that you see in binary docs formats (like with Word).
