### ISSUE TITLE
Can variables be passed to sub-templates?

### ISSUE THREAD

**Issue by bexelbie** [redhataccess/ascii_binder#95]
I have _template/page.html.erb
it includes via `<%= render("_templates/_footer.html.erb") %>` a sub-template.  That template can not use the `images_path`.

Is this a jinja limitation or something we can fix?

**Comment by Fryguy** [comment]
Does it work if you do something like:

```
<%= render("_templates/_footer.html.erb", :images_path => images_path) %>
```

Basically, render calls are a lot like function calls...they can only see the context they are given.  The page is given a bunch of paths, but those won't trickle down unless you choose to pass them down.

**Comment by bexelbie** [comment]
closing.  Thank you @Fryguy
